
import React, {useState, useMemo} from "react";
import {createRoot} from "react-dom/client";
import {Beaker, Moon, Sun, LayoutTemplate, FileText, Map, Calculator, Droplets, Factory, GitBranch, TestTube2, Wind, Flame, Thermometer, AlertTriangle, Eye, EyeOff, BookOpen} from "lucide-react";
import "./style.css";

const WATER_DENSITY=1000, R=8.314472;
const conv={Pressure:{Pa:1,kPa:1000,bar:100000,atm:101325,psi:6894.757,mmHg:133.322},Energy:{J:1,kJ:1000,cal:4.184,kcal:4184,Btu:1055.06},Mass:{g:.001,kg:1,lbm:.45359237},Volume:{L:.001,m3:1,cm3:1e-6,ft3:.0283168}};
const n=v=>{let x=Number(v);return Number.isFinite(x)?x:NaN};
const fmt=(v,d=4)=>!Number.isFinite(v)?"ERROR":(Math.abs(v)>=10000||(Math.abs(v)>0&&Math.abs(v)<.001)?v.toExponential(4):Number(v.toFixed(d)).toString());
function frac(v,name="Fraction"){let x=n(v); if(!Number.isFinite(x)) return {err:`${name} must be a number.`}; if(x<0||x>100)return {err:`${name} must be 0–1 or 0%–100%.`}; return {val:x<=1?x:x/100,label:x<=1?`${x}`:`${x}% = ${fmt(x/100)}`}}
function neg(label,v){let x=n(v); if(!Number.isFinite(x))return `${label} must be a number.`; if(x<0)return `${label} cannot be less than 0.`; return ""}
function kerr(label,c){let K=n(c)+273.15; if(!Number.isFinite(K))return `${label} must be a valid temperature.`; if(K<0)return `${label} cannot be less than 0 K.`; return ""}
function first(a){return a.filter(Boolean)[0]||""}
function Logo(){return <div className="logo"><span>ΔH</span></div>}
function Card(p){return <div className="card">{p.children}</div>}
function Header({title,text}){return <><h2>{title}</h2><p className="muted">{text}</p></>}
function Alert({msg}){return msg?<div className="alert"><AlertTriangle size={18}/>{msg}</div>:null}
function Ref({items}){return <div className="ref"><b><BookOpen size={16}/> Equation Reference</b><ul>{items.map((i,k)=><li key={k}>{i}</li>)}</ul></div>}
function Input({label,value,setValue,unit}){return <label className="field"><span>{label}</span><div><input type="number" step="any" value={value} onChange={e=>setValue(e.target.value)}/>{unit&&<em>{unit}</em>}</div></label>}
function Select({label,value,setValue,options}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>setValue(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Result({title,children}){return <div className="res"><b>{title}</b><pre>{children}</pre></div>}
function ToggleSol({err,finalAns,full}){const [show,setShow]=useState(false); if(err)return <Result title="Final Answer">ERROR: Fix invalid input first.</Result>; return <><Result title="Final Answer">{finalAns}</Result><button className="mini" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>} {show?"Hide Full Solution":"Show Full Solution"}</button>{show&&<Result title="Full Solution">{full}</Result>}</>}
function Flow({type="single"}){let map={single:["Feed","Unit","Product"],reactor:["Feed","Reactor","Outlet"],separator:["Feed","Separator","Top + Bottom"],recycle:["Fresh Feed","Mixer → Reactor → Separator","Product + Recycle/Purge"],heater:["Cold Stream","Heater","Hot Stream"]};let x=map[type];return <div className="flow"><span>{x[0]}</span><b>→</b><span className="strong">{x[1]}</span><b>→</b><span>{x[2]}</span></div>}
function Nav({id,tab,setTab,Icon,title,sub}){return <button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)}><Icon size={20}/><span><b>{title}</b><small>{sub}</small></span></button>}

function Templates({go}){let t=[["SG to kmol","sg","SG, volume, MW → moles"],["Tank overflow","tank","input/output → time"],["Reactor A→C","material","feed + conversion"],["Limiting reactant","stoich","stoich ratio"],["Ideal gas","gas","PV=nRT"],["Humidity","humidity","P, P*, Sr"],["Steam heater","steam","enthalpy duty"]];return <Card><Header title="Question Templates" text="Pick a common BASIC-A problem type."/><div className="templates">{t.map(x=><button key={x[0]} onClick={()=>go(x[1])}><b>{x[0]}</b><span>{x[2]}</span></button>)}</div></Card>}
function Equations(){let s=[["Chapter 3",["ρ=m/V","SG=ρmaterial/ρwater","n=m/MW","mass fraction=mA/mtotal","mole fraction=nA/ntotal"]],["Chapter 4",["Input+Generation−Output−Consumption=Accumulation","Steady state: Acc=0","Conversion=(nin−nout)/nin","Excess%=(nin−nstoch)/nstoch×100"]],["Chapter 5/6",["PV=nRT","Pabs=Pgauge+Patm","Pi=yiP","Raoult: Pi=xiPi*","Antoine: log10(P*)=A−B/(T+C)"]],["Chapter 7/8",["Q−Ws=ΔH","Q=mDotCpΔT","Q=mDot(hout−hin)","Wet steam: h=hf+x(hg−hf)"]]];return <Card><Header title="Equation Sheet" text="Core BASIC-A equations."/><div className="eqs">{s.map(([h,a])=><div><h3>{h}</h3><ul>{a.map(i=><li>{i}</li>)}</ul></div>)}</div></Card>}
function FlowPage(){return <Card><Header title="Flow Diagrams" text="Simple visual layouts."/><h3>Single Unit</h3><Flow/><h3>Reactor</h3><Flow type="reactor"/><h3>Separator</h3><Flow type="separator"/><h3>Recycle/Purge</h3><Flow type="recycle"/><h3>Heater</h3><Flow type="heater"/></Card>}

function SG(){const [sg,setSg]=useState("13.546"),[v,setV]=useState("175"),[mw,setMw]=useState("200.61");let err=first([neg("SG",sg),neg("Volume",v),neg("MW",mw),n(mw)===0?"MW cannot be zero.":""]);let rho=err?NaN:n(sg)*WATER_DENSITY,m=err?NaN:rho*n(v),kmol=err?NaN:m/n(mw);return <Card><Header title="SG → Density → Mass → kmol" text="Specific gravity solver."/><Ref items={["ρ=SG×ρwater","m=ρV","n=m/MW","Mass and moles cannot be negative."]}/><Alert msg={err}/><div className="grid3"><Input label="SG" value={sg} setValue={setSg}/><Input label="Volume" value={v} setValue={setV} unit="m³"/><Input label="MW" value={mw} setValue={setMw} unit="kg/kmol"/></div><ToggleSol err={err} finalAns={`n = ${fmt(kmol)} kmol`} full={`ρ=${sg}×1000=${fmt(rho)} kg/m³\nm=ρV=${fmt(m)} kg\nn=m/MW=${fmt(kmol)} kmol`}/></Card>}
function Tank(){const [i,setI]=useState("6"),[o,setO]=useState("3"),[v,setV]=useState("1");let acc=n(i)-n(o);let err=first([neg("Input",i),neg("Output",o),neg("Volume",v),acc<=0?"Input must be greater than output.":""]);let time=err?NaN:1000*n(v)/acc;return <Card><Header title="Unsteady Tank Balance" text="Input - Output = Accumulation."/><Flow/><Ref items={["Accumulation=Input−Output","Δm=ρΔV","Δt=Δm/Accumulation"]}/><Alert msg={err}/><div className="grid3"><Input label="Input" value={i} setValue={setI} unit="kg/s"/><Input label="Output" value={o} setValue={setO} unit="kg/s"/><Input label="Volume" value={v} setValue={setV} unit="m³"/></div><ToggleSol err={err} finalAns={`Time = ${fmt(time)} s`} full={`Acc=${i}-${o}=${fmt(acc)} kg/s\nΔm=1000×${v}=${fmt(1000*n(v))} kg\nΔt=Δm/Acc=${fmt(time)} s`}/></Card>}
function Material(){const [F,setF]=useState("100"),[x,setX]=useState("0.4"),[c,setC]=useState("75");let xf=frac(x,"xA"),cf=frac(c,"Conversion");let err=first([neg("Feed",F),xf.err,cf.err]);let A=n(F)*xf.val,react=A*cf.val,out=A-react;return <Card><Header title="Material Balance" text="Simple A → C reactor."/><Flow type="reactor"/><Ref items={["x/y fractions accept 0–1 or 0%–100%.","A reacted=A in×conversion","A out=A in−A reacted"]}/><Alert msg={err}/><div className="grid3"><Input label="Feed" value={F} setValue={setF}/><Input label="xA" value={x} setValue={setX} unit="0–1 or %"/><Input label="Conversion" value={c} setValue={setC} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`A out=${fmt(out)}, C out=${fmt(react)}`} full={`xA=${xf.label}\nX=${cf.label}\nAin=F×xA=${fmt(A)}\nA reacted=${fmt(react)}\nA out=${fmt(out)}`}/></Card>}
function Stoich(){const [a,setA]=useState("2"),[b,setB]=useState("1"),[A,setNA]=useState("30"),[B,setNB]=useState("80"),[e,setE]=useState("0");let err=first([neg("a",a),neg("b",b),neg("moles A",A),neg("moles B",B),neg("extent",e),n(a)===0||n(b)===0?"Coefficients cannot be zero.":""]);let req=n(A)*n(b)/n(a),ex=n(B)>req;return <Card><Header title="Stoichiometry" text="Limiting/excess reactant."/><Ref items={["Required B=nA×b/a","Moles cannot be negative.","Extent is blocked from being negative here."]}/><Alert msg={err}/><div className="grid5"><Input label="a" value={a} setValue={setA}/><Input label="b" value={b} setValue={setB}/><Input label="nA" value={A} setValue={setNA}/><Input label="nB" value={B} setValue={setNB}/><Input label="ξ" value={e} setValue={setE}/></div><ToggleSol err={err} finalAns={ex?"B excess, A limiting":"B limiting, A excess"} full={`Required B=${A}×${b}/${a}=${fmt(req)}\nActual B=${B}`}/></Card>}
function Gas(){const [P,setP]=useState("122"),[V,setV]=useState("1.25"),[T,setT]=useState("150");let K=n(T)+273.15;let err=first([neg("Pressure",P),neg("Volume",V),kerr("Temperature",T)]);let mol=err?NaN:n(P)*n(V)*1000/(R*K);return <Card><Header title="Ideal Gas" text="PV = nRT."/><Ref items={["P must be absolute.","T(K)=T(°C)+273.15","T(K) cannot be less than 0."]}/><Alert msg={err}/><div className="grid3"><Input label="P" value={P} setValue={setP} unit="kPa"/><Input label="Vdot" value={V} setValue={setV} unit="m³/min"/><Input label="T" value={T} setValue={setT} unit="°C"/></div><ToggleSol err={err} finalAns={`nDot=${fmt(mol)} mol/min`} full={`T=${fmt(K)} K\nnDot=PVDot/RT=${fmt(mol)} mol/min`}/></Card>}
function Humidity(){const [P,setP]=useState("101.325"),[ps,setPs]=useState("23.76"),[rh,setRh]=useState("60");let rf=frac(rh,"Relative humidity");let err=first([neg("Total pressure",P),neg("Vapor pressure",ps),rf.err,n(ps)>=n(P)?"P* must be less than total P.":""]);let Pi=rf.val*n(ps),y=Pi/n(P),H=y/(1-y);return <Card><Header title="Raoult / Humidity" text="One condensable component."/><Ref items={["Sr=Pi/Pi*×100","Pi=yiP","Molal humidity=yi/(1−yi)"]}/><Alert msg={err}/><div className="grid3"><Input label="P" value={P} setValue={setP}/><Input label="P*" value={ps} setValue={setPs}/><Input label="Sr" value={rh} setValue={setRh} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`yi=${fmt(y)}, H=${fmt(H)}`} full={`Sr=${rf.label}\nPi=Sr×P*=${fmt(Pi)}\nyi=Pi/P=${fmt(y)}\nH=yi/(1-yi)=${fmt(H)}`}/></Card>}
function Energy(){const [m,setM]=useState("2"),[cp,setCp]=useState("4.18"),[ti,setTi]=useState("25"),[to,setTo]=useState("80");let err=first([neg("Mass flowrate",m),neg("Cp",cp),kerr("Tin",ti),kerr("Tout",to)]);let Q=n(m)*n(cp)*(n(to)-n(ti));return <Card><Header title="Energy Balance" text="Basic heating/cooling duty."/><Flow type="heater"/><Ref items={["Q=mDotCpΔT","Mass cannot be negative.","Temperature in Kelvin cannot be less than 0."]}/><Alert msg={err}/><div className="grid4"><Input label="mDot" value={m} setValue={setM}/><Input label="Cp" value={cp} setValue={setCp}/><Input label="Tin" value={ti} setValue={setTi}/><Input label="Tout" value={to} setValue={setTo}/></div><ToggleSol err={err} finalAns={`Q=${fmt(Q)} kW`} full={`ΔT=${to}-${ti}=${fmt(n(to)-n(ti))}\nQ=${m}×${cp}×${fmt(n(to)-n(ti))}=${fmt(Q)} kW`}/></Card>}
function Steam(){const [hf,setHf]=useState("419"),[hg,setHg]=useState("2676"),[x,setX]=useState("0.85");let xf=frac(x,"Quality");let err=first([neg("hf",hf),neg("hg",hg),xf.err]);let h=n(hf)+xf.val*(n(hg)-n(hf));return <Card><Header title="Steam / Enthalpy" text="Steam table helper."/><Ref items={["Wet steam: h=hf+x(hg−hf)","Full steam table search is next heavy upgrade."]}/><Alert msg={err}/><div className="grid3"><Input label="hf" value={hf} setValue={setHf}/><Input label="hg" value={hg} setValue={setHg}/><Input label="Quality x" value={x} setValue={setX} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`h=${fmt(h)} kJ/kg`} full={`x=${xf.label}\nh=${hf}+${fmt(xf.val)}(${hg}-${hf})=${fmt(h)} kJ/kg`}/></Card>}
function Converter(){const [cat,setCat]=useState("Pressure"),[from,setFrom]=useState("Pa"),[to,setTo]=useState("kPa"),[val,setVal]=useState("1000");let keys=Object.keys(conv[cat]);React.useEffect(()=>{setFrom(Object.keys(conv[cat])[0]);setTo(Object.keys(conv[cat])[1])},[cat]);let ans=n(val)*conv[cat][from]/conv[cat][to];return <Card><Header title="Unit Converter" text="Fast conversion helper."/><div className="grid4"><Select label="Category" value={cat} setValue={setCat} options={Object.keys(conv)}/><Input label="Value" value={val} setValue={setVal}/><Select label="From" value={from} setValue={setFrom} options={keys}/><Select label="To" value={to} setValue={setTo} options={keys}/></div><ToggleSol err="" finalAns={`${val} ${from} = ${fmt(ans)} ${to}`} full={`Convert ${from} to ${to}\nAnswer=${fmt(ans)} ${to}`}/></Card>}

function App(){const [tab,setTab]=useState("templates"),[dark,setDark]=useState(false);let tabs=[["templates",LayoutTemplate,"Templates","Common problems"],["equations",FileText,"Equation Sheet","Formulas"],["flow",Map,"Flow Diagrams","Visual"],["converter",Calculator,"Converter","Units"],["sg",Droplets,"SG & kmol","Density"],["tank",Factory,"Tank","Balance"],["material",GitBranch,"Material","A→C"],["stoich",TestTube2,"Stoich","Limiting"],["gas",Wind,"Ideal Gas","PV=nRT"],["humidity",Droplets,"Humidity","Raoult"],["energy",Flame,"Energy","Q"],["steam",Thermometer,"Steam","Enthalpy"]];return <div className={dark?"app dark":"app"}><main><section className="hero"><div><div className="tag"><Beaker size={16}/> Built specifically for Chemical Engineering BASIC-A</div><div className="brand"><Logo/><div><h1>ChemSolver BASIC-A</h1><p>Given → Formula → Substitution → Final Answer</p></div></div></div><button className="toggle" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?"Light":"Dark"}</button></section><section className="content"><aside>{tabs.map(([id,I,t,s])=><Nav key={id} id={id} tab={tab} setTab={setTab} Icon={I} title={t} sub={s}/>)}</aside><section>{tab==="templates"&&<Templates go={setTab}/>} {tab==="equations"&&<Equations/>}{tab==="flow"&&<FlowPage/>}{tab==="converter"&&<Converter/>}{tab==="sg"&&<SG/>}{tab==="tank"&&<Tank/>}{tab==="material"&&<Material/>}{tab==="stoich"&&<Stoich/>}{tab==="gas"&&<Gas/>}{tab==="humidity"&&<Humidity/>}{tab==="energy"&&<Energy/>}{tab==="steam"&&<Steam/>}</section></section><footer>ChemSolver BASIC-A © Osama AJ</footer></main></div>}
createRoot(document.getElementById("root")).render(<App/>);
