
import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{Beaker,Moon,Sun,LayoutTemplate,FileText,Map,Calculator,Droplets,Factory,GitBranch,TestTube2,Wind,Flame,Thermometer,AlertTriangle,Eye,EyeOff,BookOpen,Table2,MessageSquare,ChevronDown,ChevronRight,Sparkles,Menu,X,Star,Lightbulb}from"lucide-react";
import"./style.css";

const WATER_DENSITY=1000,R=8.314472;
const conversions={Pressure:{Pa:1,kPa:1000,bar:100000,atm:101325,psi:6894.757,mmHg:133.322},Energy:{J:1,kJ:1000,cal:4.184,kcal:4184,Btu:1055.06},Mass:{g:.001,kg:1,lbm:.45359237},Volume:{L:.001,m3:1,cm3:1e-6,ft3:.0283168}};
const antoinePresets={Custom:{A:"",B:"",C:"",range:"Manual input"},Water:{A:8.07131,B:1730.63,C:233.426,range:"1–100 °C"},Benzene:{A:6.90565,B:1211.033,C:220.79,range:"8–103 °C"},Toluene:{A:6.95464,B:1344.8,C:219.48,range:"6–137 °C"},Ethanol:{A:8.20417,B:1642.89,C:230.3,range:"0–78 °C"},Acetone:{A:7.02447,B:1161,C:224,range:"Approx. common range"}};
const propertyRows=[["Water","H₂O","18.015","Steam tables","Energy / humidity / VLE"],["Air","mixture","≈28.97","Ideal gas approx.","Heating and humidity"],["Benzene","C₆H₆","78.11","SG≈0.879","Antoine / VLE"],["Toluene","C₇H₈","92.14","SG≈0.867","Benzene-toluene mixtures"],["Ethanol","C₂H₅OH","46.07","SG≈0.789","Vapor pressure"],["Acetone","C₃H₆O","58.08","SG≈0.791","Vapor pressure"]];
const toolInfo={templates:["Templates","Common problem shortcuts"],equations:["Equation Sheet","Core formulas"],advisor:["Equation Advisor","Which equation should I use?"],flow:["Flow Diagrams","Visual layouts"],tables:["Tables","Quick references"],converter:["Unit Converter","Fast conversions"],sg:["SG & kmol","Density → moles"],tank:["Tank Balance","Accumulation"],material:["Material Balance","A → C reactor"],stoich:["Stoichiometry","Limiting/excess"],gas:["Ideal Gas","PV = nRT"],humidity:["Humidity","Raoult / gas-vapor"],antoine:["Antoine","Vapor pressure"],energy:["Energy Balance","Heat duty"],steam:["Steam / Enthalpy","Steam helper"]};
const defaultFavs=["antoine","gas","humidity","energy"];

const n=v=>{const x=Number(v);return Number.isFinite(x)?x:NaN};
const fmt=(v,d=4)=>!Number.isFinite(v)?"ERROR":(Math.abs(v)>=10000||(Math.abs(v)>0&&Math.abs(v)<.001)?v.toExponential(4):Number(v.toFixed(d)).toString());
const first=a=>a.filter(Boolean)[0]||"";
function neg(l,v){const x=n(v);if(!Number.isFinite(x))return`${l} must be a valid number.`;if(x<0)return`${l} cannot be less than 0.`;return""}
function kerr(l,c){const K=n(c)+273.15;if(!Number.isFinite(K))return`${l} must be a valid temperature.`;if(K<0)return`${l} cannot be less than 0 K.`;return""}
function frac(v,name="Fraction"){const x=n(v);if(!Number.isFinite(x))return{err:`${name} must be a valid number.`,val:NaN,label:"ERROR"};if(x<0||x>100)return{err:`${name} must be between 0–1 or 0%–100%.`,val:NaN,label:"ERROR"};if(x<=1)return{err:"",val:x,label:`${x}`};return{err:"",val:x/100,label:`${x}% = ${fmt(x/100)}`}}

function Logo(){return <div className="logo"><span>ΔH</span></div>}
function Card({children}){return <div className="card">{children}</div>}
function Header({title,text}){return <div className="section-head"><h2>{title}</h2><p>{text}</p></div>}
function Alert({msg}){return msg?<div className="alert"><AlertTriangle size={18}/><span>{msg}</span></div>:null}
function MathLine({children}){return <div className="math-line">{children}</div>}
function Ref({items}){return <div className="ref"><b><BookOpen size={16}/> Equation Reference</b><div className="ref-list">{items.map((i,k)=><MathLine key={k}>{i}</MathLine>)}</div></div>}
function Mistakes({items}){return <div className="mistakes"><b><AlertTriangle size={16}/> Common Mistakes</b><ul>{items.map((i,k)=><li key={k}>{i}</li>)}</ul></div>}
function Input({label,value,setValue,unit,type="number"}){return <label className="field"><span>{label}</span><div><input type={type} step="any" value={value} onChange={e=>setValue(e.target.value)}/>{unit&&<em>{unit}</em>}</div></label>}
function Select({label,value,setValue,options}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>setValue(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Result({title,children}){return <div className="res"><b>{title}</b><pre>{children}</pre></div>}
function ToggleSol({err,finalAns,full}){const[show,setShow]=useState(false);if(err)return<Result title="Final Answer">ERROR: Fix invalid input first.</Result>;return<><Result title="Final Answer">{finalAns}</Result><button className="mini" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>} {show?"Hide Full Solution":"Show Full Solution"}</button>{show&&<Result title="Full Solution">{full}</Result>}</>}
function Flow({type="single"}){const map={single:["Feed","Unit","Product"],reactor:["Feed","Reactor","Outlet"],separator:["Feed","Separator","Top + Bottom"],recycle:["Fresh Feed","Mixer → Reactor → Separator","Product + Recycle/Purge"],heater:["Cold Stream","Heater","Hot Stream"]};const x=map[type];return <div className="flow"><span>{x[0]}</span><b>→</b><span className="strong">{x[1]}</span><b>→</b><span>{x[2]}</span></div>}

function FavoriteButton({id,favorites,setFavorites}){const active=favorites.includes(id);return <button className={active?"fav active":"fav"} onClick={()=>setFavorites(active?favorites.filter(x=>x!==id):[...favorites,id])}><Star size={17} fill={active?"currentColor":"none"}/></button>}
function FavoritesBar({favorites,setTab}){const list=favorites.filter(id=>toolInfo[id]);if(!list.length)return null;return <div className="favorites"><b><Star size={16}/> Favorites</b><div>{list.map(id=><button key={id} onClick={()=>{setTab(id);window.scrollTo({top:0,behavior:"smooth"})}}>{toolInfo[id][0]}</button>)}</div></div>}

const groups=[{name:"Start Here",icon:LayoutTemplate,items:[["templates","Templates","Common problems",LayoutTemplate],["equations","Equation Sheet","Core formulas",FileText],["advisor","Equation Advisor","Which equation?",Lightbulb],["flow","Flow Diagrams","Visual layouts",Map]]},{name:"Basics",icon:Calculator,items:[["converter","Unit Converter","Fast conversions",Calculator],["sg","SG & kmol","Density → moles",Droplets]]},{name:"Balances",icon:Factory,items:[["tank","Tank Balance","Accumulation",Factory],["material","Material Balance","A → C reactor",GitBranch],["stoich","Stoichiometry","Limiting/excess",TestTube2]]},{name:"Thermo / VLE",icon:Thermometer,items:[["gas","Ideal Gas","PV = nRT",Wind],["humidity","Raoult / Humidity","Gas-vapor",Droplets],["antoine","Antoine Equation","Manual + presets",Calculator],["energy","Energy Balance","Q duty",Flame],["steam","Steam / Enthalpy","Steam helper",Thermometer]]},{name:"Resources",icon:Table2,items:[["tables","Tables","Quick references",Table2]]}];

function SideNav({tab,setTab,mobileOpen,setMobileOpen,favorites,setFavorites}){const[open,setOpen]=useState({"Start Here":true,"Basics":true,"Balances":true,"Thermo / VLE":true,"Resources":true});const pick=id=>{setTab(id);setMobileOpen(false);window.scrollTo({top:0,behavior:"smooth"})};return <aside className={`sidebar ${mobileOpen?"mobile-open":""}`}><div className="mobile-menu-head"><b>Tools Menu</b><button onClick={()=>setMobileOpen(false)}><X size={20}/></button></div>{groups.map(g=>{const Icon=g.icon;return <div className="nav-group" key={g.name}><button className="group-btn" onClick={()=>setOpen({...open,[g.name]:!open[g.name]})}><span><Icon size={17}/> {g.name}</span>{open[g.name]?<ChevronDown size={17}/>:<ChevronRight size={17}/>}</button>{open[g.name]&&<div className="group-items">{g.items.map(([id,title,sub,ItemIcon])=><div className="nav-row" key={id}><button className={tab===id?"nav active":"nav"} onClick={()=>pick(id)}><ItemIcon size={19}/><span><b>{title}</b><small>{sub}</small></span></button><FavoriteButton id={id} favorites={favorites} setFavorites={setFavorites}/></div>)}</div>}</div>})}<div className="rules"><b>Validation Rules</b><br/>Mass, moles, pressure, volume, flowrate, SG, Cp cannot be negative. T(K) cannot be less than 0. Fractions accept 0–1 or 0%–100%.</div></aside>}
function MobileQuickBar({setTab}){return <div className="quickbar">{[["Templates","templates"],["Advisor","advisor"],["Antoine","antoine"],["Steam","steam"]].map(([l,id])=><button key={id} onClick={()=>{setTab(id);window.scrollTo({top:0,behavior:"smooth"})}}>{l}</button>)}</div>}

function Templates({go}){const items=[["SG to kmol","sg","SG, volume, MW → moles"],["Tank overflow","tank","input/output → time"],["Reactor A→C","material","feed + conversion"],["Limiting reactant","stoich","stoich ratio"],["Ideal gas","gas","PV=nRT"],["Humidity","humidity","P, P*, Sr"],["Antoine Psat","antoine","manual constants or preset"],["Steam quality","steam","hf, hg, x → h"]];return <Card><Header title="Question Templates" text="Shortcuts for common BASIC-A problem types."/><div className="templates">{items.map(([t,id,d])=><button key={t} onClick={()=>go(id)}><b>{t}</b><span>{d}</span></button>)}</div></Card>}
function Equations(){const sections=[["Chapter 3",["ρ = m / V","SG = ρmaterial / ρwater","n = m / MW","mass fraction = mA / mtotal","mole fraction = nA / ntotal"]],["Chapter 4",["Input + Generation − Output − Consumption = Accumulation","Steady state: Accumulation = 0","Conversion = (nin − nout) / nin","Excess% = (nin − nstoch) / nstoch × 100"]],["Chapter 5/6",["PV = nRT","Pabs = Pgauge + Patm","Pi = yiP","Raoult: Pi = xiPi*","Antoine: log10(Psat) = A − B / (T + C)"]],["Chapter 7/8",["Q − Ws = ΔH","Q = ṁCpΔT","Q = ṁ(hout − hin)","Wet steam: h = hf + x(hg − hf)"]]];return <Card><Header title="Equation Sheet" text="Core equations in one clean page."/><div className="eqs">{sections.map(([h,a])=><div className="eq-card" key={h}><h3>{h}</h3>{a.map(x=><MathLine key={x}>{x}</MathLine>)}</div>)}</div></Card>}
function Advisor({go}){const[problem,setProblem]=useState("vapor-pressure");const map={"vapor-pressure":{eq:"Antoine Equation",formula:"log10(Psat) = A − B / (T + C)",tool:"antoine",why:"Use it when you have Antoine constants and temperature, or need vapor pressure."},"ideal-gas":{eq:"Ideal Gas Law",formula:"PV = nRT",tool:"gas",why:"Use it when gas pressure, volume, moles, and temperature are related."},"humidity":{eq:"Raoult / Humidity Relations",formula:"Sr = Pi / Pi* × 100",tool:"humidity",why:"Use it for gas-vapor mixtures, relative humidity, and molal humidity."},"material":{eq:"Material Balance",formula:"Input + Generation − Output − Consumption = Accumulation",tool:"material",why:"Use it for process streams, reactions, conversion, and outlet amounts."},"energy":{eq:"Energy Balance",formula:"Q − Ws = ΔH",tool:"energy",why:"Use it when heat, shaft work, or enthalpy changes are involved."},"steam":{eq:"Steam / Enthalpy Relation",formula:"h = hf + x(hg − hf)",tool:"steam",why:"Use it for wet steam, steam quality, or table-based enthalpy."}};const r=map[problem];return <Card><Header title="Which Equation Should I Use?" text="Pick what your problem looks like. The site suggests the equation and tool."/><div className="grid3"><Select label="Problem type" value={problem} setValue={setProblem} options={Object.keys(map)}/></div><div className="advisor-card"><h3>{r.eq}</h3><MathLine>{r.formula}</MathLine><p>{r.why}</p><button className="mini" onClick={()=>go(r.tool)}>Open {toolInfo[r.tool][0]}</button></div></Card>}
function FlowPage(){return <Card><Header title="Flow Diagrams" text="Simple visual layouts for process thinking."/><h3>Single Unit</h3><Flow/><h3>Reactor</h3><Flow type="reactor"/><h3>Separator</h3><Flow type="separator"/><h3>Recycle / Purge</h3><Flow type="recycle"/><h3>Heater</h3><Flow type="heater"/></Card>}
function TablesPage(){return <Card><Header title="Tables & Resources" text="Quick references. Use official course materials for complete tables."/><div className="notice">Copyright-safe: this page does not host the full textbook PDF. It only includes small quick-reference values.</div><h3>Common Property Quick Table</h3><div className="table-wrap"><table><thead><tr><th>Compound</th><th>Formula</th><th>MW</th><th>Data note</th><th>Use</th></tr></thead><tbody>{propertyRows.map((r,i)=><tr key={i}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div><h3>Antoine Presets</h3><div className="table-wrap"><table><thead><tr><th>Compound</th><th>A</th><th>B</th><th>C</th><th>Range</th></tr></thead><tbody>{Object.entries(antoinePresets).filter(([k])=>k!=="Custom").map(([name,c])=><tr key={name}><td>{name}</td><td>{c.A}</td><td>{c.B}</td><td>{c.C}</td><td>{c.range}</td></tr>)}</tbody></table></div></Card>}
function FeedbackFooter(){const[name,setName]=useState(""),[msg,setMsg]=useState(""),[type,setType]=useState("Feature suggestion");const body=encodeURIComponent(`Name: ${name||"Anonymous"}\nType: ${type}\n\nMessage:\n${msg}`);const mail=`mailto:thebestosama69420@gmail.com?subject=ChemSolver BASIC-A Feedback&body=${body}`;return <section className="feedback-footer"><div><h2>Feedback & Suggestions</h2><p>Found a bug or have an idea? Send a comment. No backend yet, so this opens your email app.</p></div><div className="feedback-grid"><Input label="Name optional" value={name} setValue={setName} type="text"/><Select label="Type" value={type} setValue={setType} options={["Feature suggestion","Bug report","Wrong calculation","UI improvement","Other"]}/></div><label className="field"><span>Your comment</span><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Write what should be improved..."/></label><a className="mail-btn" href={mail}><MessageSquare size={18}/> Send feedback by email</a></section>}

function Converter(){const[cat,setCat]=useState("Pressure");const keys=Object.keys(conversions[cat]);const[from,setFrom]=useState(keys[0]);const[to,setTo]=useState(keys[1]);const[val,setVal]=useState("1000");useEffect(()=>{const k=Object.keys(conversions[cat]);setFrom(k[0]);setTo(k[1])},[cat]);const ans=n(val)*conversions[cat][from]/conversions[cat][to];return <Card><Header title="Unit Converter" text="Fast conversion helper."/><div className="grid4"><Select label="Category" value={cat} setValue={setCat} options={Object.keys(conversions)}/><Input label="Value" value={val} setValue={setVal}/><Select label="From" value={from} setValue={setFrom} options={keys}/><Select label="To" value={to} setValue={setTo} options={keys}/></div><ToggleSol err="" finalAns={`${val} ${from} = ${fmt(ans)} ${to}`} full={`Convert ${from} to ${to}\nAnswer = ${fmt(ans)} ${to}`}/></Card>}
function SG(){const[sg,setSg]=useState("13.546"),[v,setV]=useState("175"),[mw,setMw]=useState("200.61");const err=first([neg("SG",sg),neg("Volume",v),neg("MW",mw),n(mw)===0?"MW cannot be zero.":""]);const rho=err?NaN:n(sg)*WATER_DENSITY,m=err?NaN:rho*n(v),kmol=err?NaN:m/n(mw);return <Card><Header title="SG → Density → Mass → kmol" text="Specific gravity solver."/><Ref items={["ρ = SG × ρwater","m = ρV","n = m / MW","Mass and moles cannot be negative."]}/><Alert msg={err}/><div className="grid3"><Input label="SG" value={sg} setValue={setSg}/><Input label="Volume" value={v} setValue={setV} unit="m³"/><Input label="MW" value={mw} setValue={setMw} unit="kg/kmol"/></div><ToggleSol err={err} finalAns={`n = ${fmt(kmol)} kmol`} full={`ρ = ${sg} × 1000 = ${fmt(rho)} kg/m³\nm = ρV = ${fmt(m)} kg\nn = m / MW = ${fmt(kmol)} kmol`}/><Mistakes items={["Do not use SG directly as density unless water density is included.","Check the molecular weight units before dividing mass by MW."]}/></Card>}
function Tank(){const[i,setI]=useState("6"),[o,setO]=useState("3"),[v,setV]=useState("1");const acc=n(i)-n(o);const err=first([neg("Input",i),neg("Output",o),neg("Volume",v),acc<=0?"Input must be greater than output.":""]);const time=err?NaN:1000*n(v)/acc;return <Card><Header title="Unsteady Tank Balance" text="Input − Output = Accumulation."/><Flow/><Ref items={["Accumulation = Input − Output","Δm = ρΔV","Δt = Δm / Accumulation"]}/><Alert msg={err}/><div className="grid3"><Input label="Input" value={i} setValue={setI} unit="kg/s"/><Input label="Output" value={o} setValue={setO} unit="kg/s"/><Input label="Volume" value={v} setValue={setV} unit="m³"/></div><ToggleSol err={err} finalAns={`Time = ${fmt(time)} s`} full={`Accumulation = ${i} − ${o} = ${fmt(acc)} kg/s\nΔm = 1000 × ${v} = ${fmt(1000*n(v))} kg\nΔt = Δm / Accumulation = ${fmt(time)} s`}/><Mistakes items={["If output is greater than input, the tank is not filling.","Keep volume and density units consistent."]}/></Card>}
function Material(){const[F,setF]=useState("100"),[x,setX]=useState("0.4"),[c,setC]=useState("75");const xf=frac(x,"xA"),cf=frac(c,"Conversion");const err=first([neg("Feed",F),xf.err,cf.err]);const A=n(F)*xf.val,reacted=A*cf.val,out=A-reacted;return <Card><Header title="Material Balance" text="Simple A → C reactor."/><Flow type="reactor"/><Ref items={["x and y fractions accept 0–1 or 0%–100%.","A reacted = A in × conversion","A out = A in − A reacted"]}/><Alert msg={err}/><div className="grid3"><Input label="Feed" value={F} setValue={setF}/><Input label="xA" value={x} setValue={setX} unit="0–1 or %"/><Input label="Conversion" value={c} setValue={setC} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`A out = ${fmt(out)}, C out = ${fmt(reacted)}`} full={`xA = ${xf.label}\nX = ${cf.label}\nAin = F × xA = ${fmt(A)}\nA reacted = ${fmt(reacted)}\nA out = ${fmt(out)}`}/><Mistakes items={["Do not use 75 as conversion unless you mean 75%.","Check whether the question gives mole fraction or mass fraction."]}/></Card>}
function Stoich(){const[a,setA]=useState("2"),[b,setB]=useState("1"),[A,setNA]=useState("30"),[B,setNB]=useState("80"),[e,setE]=useState("0");const err=first([neg("a",a),neg("b",b),neg("moles A",A),neg("moles B",B),neg("extent",e),n(a)===0||n(b)===0?"Coefficients cannot be zero.":""]);const req=n(A)*n(b)/n(a),ex=n(B)>req;return <Card><Header title="Stoichiometry" text="Limiting/excess reactant."/><Ref items={["Required B = nA × b/a","Moles cannot be negative.","Extent is blocked from being negative here."]}/><Alert msg={err}/><div className="grid5"><Input label="a" value={a} setValue={setA}/><Input label="b" value={b} setValue={setB}/><Input label="nA" value={A} setValue={setNA}/><Input label="nB" value={B} setValue={setNB}/><Input label="ξ" value={e} setValue={setE}/></div><ToggleSol err={err} finalAns={ex?"B excess, A limiting":"B limiting, A excess"} full={`Required B = ${A} × ${b}/${a} = ${fmt(req)}\nActual B = ${B}`}/><Mistakes items={["Use stoichiometric coefficients, not feed mole fractions.","The limiting reactant is based on required vs available amount."]}/></Card>}
function Gas(){const[P,setP]=useState("122"),[V,setV]=useState("1.25"),[T,setT]=useState("150");const K=n(T)+273.15;const err=first([neg("Pressure",P),neg("Volume",V),kerr("Temperature",T)]);const mol=err?NaN:n(P)*n(V)*1000/(R*K);return <Card><Header title="Ideal Gas" text="PV = nRT."/><Ref items={["P must be absolute.","T(K) = T(°C) + 273.15","T(K) cannot be less than 0."]}/><Alert msg={err}/><div className="grid3"><Input label="P" value={P} setValue={setP} unit="kPa"/><Input label="Vdot" value={V} setValue={setV} unit="m³/min"/><Input label="T" value={T} setValue={setT} unit="°C"/></div><ToggleSol err={err} finalAns={`nDot = ${fmt(mol)} mol/min`} full={`T = ${fmt(K)} K\nnDot = PVDot / RT = ${fmt(mol)} mol/min`}/><Mistakes items={["Use absolute pressure, not gauge pressure.","Convert temperature to Kelvin before applying PV = nRT.","Make sure volume is converted to L when using R = 8.314 kPa·L/(mol·K)."]}/></Card>}
function Humidity(){const[P,setP]=useState("101.325"),[ps,setPs]=useState("23.76"),[rh,setRh]=useState("60");const rf=frac(rh,"Relative humidity");const err=first([neg("Total pressure",P),neg("Vapor pressure",ps),rf.err,n(ps)>=n(P)?"P* must be less than total P.":""]);const Pi=rf.val*n(ps),y=Pi/n(P),H=y/(1-y);return <Card><Header title="Raoult / Humidity" text="One condensable component."/><Ref items={["Sr = Pi / Pi* × 100","Pi = yiP","Molal humidity = yi / (1 − yi)"]}/><Alert msg={err}/><div className="grid3"><Input label="P" value={P} setValue={setP}/><Input label="P*" value={ps} setValue={setPs}/><Input label="Sr" value={rh} setValue={setRh} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`yi = ${fmt(y)}, H = ${fmt(H)}`} full={`Sr = ${rf.label}\nPi = Sr × P* = ${fmt(Pi)}\nyi = Pi / P = ${fmt(y)}\nH = yi / (1 − yi) = ${fmt(H)}`}/><Mistakes items={["Do not forget to convert relative humidity percentage to fraction.","Vapor pressure cannot be larger than total pressure.","Molal humidity is per dry gas, not per total gas."]}/></Card>}
function Antoine(){const[compound,setCompound]=useState("Custom");const preset=antoinePresets[compound];const[A,setA]=useState("8.07131"),[B,setB]=useState("1730.63"),[C,setC]=useState("233.426"),[T,setT]=useState("25");useEffect(()=>{if(compound!=="Custom"){setA(String(preset.A));setB(String(preset.B));setC(String(preset.C))}},[compound]);const err=first([neg("A",A),neg("B",B),neg("C",C),kerr("Temperature",T),n(T)+n(C)===0?"T + C cannot be zero.":""]);const logP=n(A)-n(B)/(n(T)+n(C));const p=err?NaN:Math.pow(10,logP),kPa=p*.133322;return <Card><Header title="Antoine Equation" text="Calculate vapor pressure from A, B, C, and temperature. Presets are optional."/><Ref items={["log10(Psat) = A − B / (T + C)","T is in °C for these constants.","Output is mmHg then converted to kPa.","Use Custom for compounds not listed."]}/><Alert msg={err}/><div className="grid4"><Select label="Preset" value={compound} setValue={setCompound} options={Object.keys(antoinePresets)}/><Input label="A" value={A} setValue={setA}/><Input label="B" value={B} setValue={setB}/><Input label="C" value={C} setValue={setC}/></div><div className="grid3"><Input label="Temperature" value={T} setValue={setT} unit="°C"/></div><div className="notice">Mode: {compound}. Validity note: {preset.range}. For unknown compounds, choose Custom and enter A, B, C manually.</div><ToggleSol err={err} finalAns={`Psat = ${fmt(p)} mmHg = ${fmt(kPa)} kPa`} full={`log10(Psat) = ${A} − ${B}/(${T}+${C})\nlog10(Psat) = ${fmt(logP)}\nPsat = ${fmt(p)} mmHg\nPsat = ${fmt(p)} × 0.133322 = ${fmt(kPa)} kPa`}/><Mistakes items={["Check that Antoine constants match the temperature range.","Do not mix ln constants with log10 constants.","These presets use °C and output mmHg before conversion."]}/></Card>}
function Energy(){const[m,setM]=useState("2"),[cp,setCp]=useState("4.18"),[ti,setTi]=useState("25"),[to,setTo]=useState("80");const err=first([neg("Mass flowrate",m),neg("Cp",cp),kerr("Tin",ti),kerr("Tout",to)]);const Q=n(m)*n(cp)*(n(to)-n(ti));return <Card><Header title="Energy Balance" text="Basic heating/cooling duty."/><Flow type="heater"/><Ref items={["Q = ṁCpΔT","Mass cannot be negative.","Temperature in Kelvin cannot be less than 0."]}/><Alert msg={err}/><div className="grid4"><Input label="mDot" value={m} setValue={setM}/><Input label="Cp" value={cp} setValue={setCp}/><Input label="Tin" value={ti} setValue={setTi}/><Input label="Tout" value={to} setValue={setTo}/></div><ToggleSol err={err} finalAns={`Q = ${fmt(Q)} kW`} full={`ΔT = ${to} − ${ti} = ${fmt(n(to)-n(ti))}\nQ = ${m} × ${cp} × ${fmt(n(to)-n(ti))} = ${fmt(Q)} kW`}/><Mistakes items={["Check whether Cp is per kg or per mol.","A negative Q can mean cooling or heat removal.","Use enthalpy tables when phase change is involved."]}/></Card>}
function Steam(){const[hf,setHf]=useState("419"),[hg,setHg]=useState("2676"),[x,setX]=useState("0.85");const xf=frac(x,"Quality");const err=first([neg("hf",hf),neg("hg",hg),xf.err]);const h=n(hf)+xf.val*(n(hg)-n(hf));return <Card><Header title="Steam / Enthalpy" text="Steam table helper."/><Ref items={["Wet steam: h = hf + x(hg − hf)","Full steam table search is next heavy upgrade."]}/><Alert msg={err}/><div className="grid3"><Input label="hf" value={hf} setValue={setHf}/><Input label="hg" value={hg} setValue={setHg}/><Input label="Quality x" value={x} setValue={setX} unit="0–1 or %"/></div><ToggleSol err={err} finalAns={`h = ${fmt(h)} kJ/kg`} full={`x = ${xf.label}\nh = ${hf} + ${fmt(xf.val)}(${hg} − ${hf}) = ${fmt(h)} kJ/kg`}/><Mistakes items={["Quality x must be between 0 and 1.","Use saturated tables only for saturated mixtures.","For superheated steam, use superheated tables instead."]}/></Card>}

function App(){const[tab,setTab]=useState("templates"),[dark,setDark]=useState(false),[mobileOpen,setMobileOpen]=useState(false);const[favorites,setFavorites]=useState(()=>{try{return JSON.parse(localStorage.getItem("chemsolver-favorites"))||defaultFavs}catch{return defaultFavs}});useEffect(()=>localStorage.setItem("chemsolver-favorites",JSON.stringify(favorites)),[favorites]);return <div className={dark?"app dark":"app"}><main><section className="hero"><div><div className="tag"><Sparkles size={16}/> Built specifically for Chemical Engineering BASIC-A</div><div className="brand"><Logo/><div><h1>ChemSolver BASIC-A</h1><p>Smart assistant tools. Better equations. Faster review.</p></div></div></div><div className="hero-actions"><button className="toggle menu-btn" onClick={()=>setMobileOpen(true)}><Menu/> Menu</button><button className="toggle" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?"Light":"Dark"}</button></div></section><MobileQuickBar setTab={setTab}/><FavoritesBar favorites={favorites} setTab={setTab}/><section className="content"><SideNav tab={tab} setTab={setTab} mobileOpen={mobileOpen} setMobileOpen={setMobileOpen} favorites={favorites} setFavorites={setFavorites}/>{mobileOpen&&<div className="overlay" onClick={()=>setMobileOpen(false)}/>}<section className="panel">{tab==="templates"&&<Templates go={setTab}/>} {tab==="equations"&&<Equations/>}{tab==="advisor"&&<Advisor go={setTab}/>} {tab==="flow"&&<FlowPage/>}{tab==="tables"&&<TablesPage/>}{tab==="converter"&&<Converter/>}{tab==="sg"&&<SG/>}{tab==="tank"&&<Tank/>}{tab==="material"&&<Material/>}{tab==="stoich"&&<Stoich/>}{tab==="gas"&&<Gas/>}{tab==="humidity"&&<Humidity/>}{tab==="antoine"&&<Antoine/>}{tab==="energy"&&<Energy/>}{tab==="steam"&&<Steam/>}</section></section><FeedbackFooter/><footer>ChemSolver BASIC-A © Osama AJ</footer></main></div>}
createRoot(document.getElementById("root")).render(<App/>);
